operateur(graphe,a,b).
operateur(graphe,a,f).
operateur(graphe,a,g).
operateur(graphe,b,c).
operateur(graphe,b,e).
operateur(graphe,b,f).
operateur(graphe,c,f).
operateur(graphe,c,g).
operateur(graphe,e,h).
operateur(graphe,e,l).
operateur(graphe,f,e).
operateur(graphe,f,h).
operateur(graphe,f,i).
operateur(graphe,g,f).
operateur(graphe,g,i).
operateur(graphe,h,i).
operateur(graphe,h,k).
operateur(graphe,h,l).
operateur(graphe,i,j).
operateur(graphe,j,g).
operateur(graphe,j,m).
operateur(graphe,j,o).
operateur(graphe,k,n).
operateur(graphe,l,j).
operateur(graphe,l,k).
operateur(graphe,l,o).
operateur(graphe,l,p).
operateur(graphe,m,p).
operateur(graphe,m,q).
operateur(graphe,n,o).
operateur(graphe,n,p).
operateur(graphe,n,q).
operateur(graphe,o,m).
operateur(graphe,o,p).
operateur(graphe,o,q).


h(a,17).
h(b,15).
h(c,15).
h(e,12).
h(f,17).
h(g,15).
h(h,11).
h(i,9).
h(j,7).
h(k,9).
h(l,8).
h(m,2).
h(n,7).
h(o,6).
h(p,0).
h(q,0).

but(p).
but(q).